### ISSUE TITLE
Translate Attribute names to simpler versions

### ISSUE THREAD

**Issue by joshua-reynolds** [WFRCAnalytics/UT_Sales_Tax_Analysis#1]
Translate Attribute names to simpler versions

Fields

ACCOMMODATION_721	
ADMIN__SUPPORT__WASTE_MANAG__REMED_SERVICES_56	
AGRICULTURE_FORESTRY_FISHING__HUNTING_11	
ARTS_ENTERTAINMENT_AND_RECREATION_71	
CONSTRUCTION_23	
EDUCATIONAL_SERVICES_61	
FINANCE__INSURANCE_52	
FOOD_SERVICES__DRINKING_PLACES_722	
HEALTH_CARE__SOCIAL_ASSISTANCE_62	
INFORMATION_51	
MANAGEMENT_OF_COMPANIES__ENTERPRISES_55	
MANUFACTURING_31_33	
MINING_QUARRYING__OIL__GAS_EXTRACTION_21	
OTHER_SERVICES_EXCEPT_PUBLIC_ADMINISTRATION_81	
PRIOR_PERIOD_PAYMENTS__REFUNDS	PRIVATE_MOTOR_VEHICLE_SALES	PROFESSIONAL_SCIENTIFIC__TECHNICAL_SERVICES_54	
PUBLIC_ADMINISTRATION_92	
REAL_ESTATE_RENTAL__LEASING_53	
RETAIL_BUILD_MATERIAL_GARDEN_EQUIP__SUPPLIES_DEALERS_444	
RETAIL_CLOTHING__CLOTHING_ACCESSORIES_STORES_448	
RETAIL_ELECTRONICS__APPLIANCE_STORES_443	
RETAIL_FOOD__BEVERAGE_STORES_445	
RETAIL_FURNITURE__HOME_FURNISHINGS_STORES_442	
RETAIL_GASOLINE_STATIONS_447	
RETAIL_GENERAL_MERCHANDISE_STORES_452	
RETAIL_HEALTH__PERSONAL_CARE_STORES_446	
RETAIL_MISCELLANEOUS_STORE_RETAILERS_453	
RETAIL_MOTOR_VEHICLE__PARTS_DEALERS_441	
RETAIL_NONSTORE_RETAILERS_454	
RETAIL_SPORTING_GOODS_HOBBY_MUSIC__BOOK_STORES_451	
SPECIAL_EVENT_SALES	
TRANSPORTATION__WAREHOUSING_48_49	
UNKNOWN_NONCLASSIFIABLE	
UTILITIES_22	
WHOLESALE_TRADE_DURABLE_GOODS_423	
WHOLESALE_TRADE_ELECTRONIC_MARKETS_425	
WHOLESALE_TRADE_NONDURABLE_GOODS_424

**Comment by bert-granberg** [comment]
Here ya go...let's sort by the new field names which have a one character general sector identifier

https://docs.google.com/spreadsheets/d/1wIBsdYqAjNs2jh0JcjV9aGAmcqx8P8yTToTnDnr2-vM/edit#gid=592717441

...and add the '_19' and '_20' to the ends

**Comment by joshua-reynolds** [comment]
Thanks! I like the identifier addition, it will be useful in arcade.
